import {validateAutomaticEnding} from './automaticEnding.js';
import {branchScope} from './branchExchange.js';

const stable=v=>JSON.stringify(v,(_,x)=>x&&typeof x==='object'&&!Array.isArray(x)?Object.fromEntries(Object.keys(x).sort().map(k=>[k,x[k]])):x);
async function hash(v){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(stable(v))))].map(x=>x.toString(16).padStart(2,'0')).join('');}
const clone=v=>structuredClone(v);
const slug=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/gi,'d').toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');
const meaningful=v=>v!==null&&v!==undefined&&v!==false&&v!==''&&(typeof v!=='object'||Object.values(v).some(meaningful));
function inbound(game,ids,root){const rows=[];for(const [id,n] of Object.entries(game.nodes)){if(ids.includes(id))continue;for(const [i,c] of (n.choices||[]).entries()){if(id===root.sceneId&&i===root.choiceIndex)continue;for(const target of [c.targetNodeId,c.diceRoll?.successTarget,c.diceRoll?.failTarget,c.diceRoll?.targetNodeId])if(ids.includes(target))rows.push([id,i,target]);}for(const k of ['winTarget','loseTarget','fleeTarget'])if(ids.includes(n.combat?.[k]))rows.push([id,k,n.combat[k]]);}return rows;}
async function fingerprint(game,root){const scope=branchScope(game,root);return hash({root,choice:game.nodes[root.sceneId].choices[root.choiceIndex],nodes:scope.ids.map(id=>[id,game.nodes[id]]),shared:scope.shared,inbound:inbound(game,scope.ids,root),stats:game.meta?.statsConfig,initialStats:game.meta?.initialStats});}
const commonFields=new Set(['id','text','speaker','bgImage','npcAvatar','choices','isEnding','endingType','systemPopup','automaticEnding','statRequirements','workshopPosition','workshopRole','workshopTitle','workshopHint']);
const choiceFields=new Set(['text','targetNodeId','statModifiers','statRequirements','statRequirementsMax','grantFlag','grantFlags','requiresFlag','requiresFlagAbsent','grantItem','requiresItem','removeItem','npcAffinity','requiresNpcAffinity','requiresNpcAffinityMax','systemPopup','workshopPosition','workshopContinuation','exp','systemPoints','unlockSkill','completeQuestId','label']);
function assertSupported(node,id){for(const [k,v] of Object.entries(node)){if(!commonFields.has(k)&&meaningful(v))throw new Error(`Cảnh ${id} có cơ chế ${k} chưa hỗ trợ xuất dạng viết lại tự do. Chưa xuất để tránh mất luật.`);}if(meaningful(node.statRequirements))throw new Error(`Cảnh ${id} có điều kiện trên cảnh chưa hỗ trợ.`);for(const c of node.choices||[])for(const [k,v] of Object.entries(c))if(!choiceFields.has(k)&&meaningful(v))throw new Error(`Cảnh ${id} có cơ chế đáp án ${k} chưa hỗ trợ viết lại tự do.`);}
function oneLine(value,label){if(/[\r\n]/.test(value||''))throw new Error(`${label} có nhiều dòng; chưa thể xuất an toàn theo cú pháp một dòng.`);return value||'';}
function effects(c,labels){const lines=[];for(const [field,symbol] of [['statModifiers',''],['statRequirements','>='],['statRequirementsMax','<=']])for(const [key,value] of Object.entries(c[field]||{})){const label=labels[key]||key;lines.push(`→ ${symbol?'Cần ':''}${label} ${symbol?symbol+' ':value>=0?'+':''}${value}`);}
 for(const [key,label] of [['requiresFlag','Cần cờ'],['requiresFlagAbsent','Cần không có cờ'],['grantItem','Vật phẩm'],['requiresItem','Cần vật phẩm'],['removeItem','Mất vật phẩm'],['unlockSkill','Kỹ năng'],['completeQuestId','Hoàn thành nhiệm vụ'],['label','Nhãn đáp án']])if(c[key])lines.push(`→ ${label}: ${oneLine(c[key],label)}`);
 for(const flag of new Set([c.grantFlag,...(c.grantFlags||[])].filter(Boolean)))lines.push(`→ Cờ: ${oneLine(flag,'Cờ')}`);
 for(const [key,label] of [['npcAffinity','Hảo cảm'],['requiresNpcAffinity','Cần hảo cảm'],['requiresNpcAffinityMax','Cần hảo cảm tối đa']])for(const [name,value] of Object.entries(c[key]||{}))lines.push(`→ ${label}: ${name} | ${value}`);
 for(const [key,label] of [['exp','Kinh nghiệm'],['systemPoints','Điểm hệ thống']])if(c[key]!=null)lines.push(`→ ${label}: ${c[key]}`);
 if(c.systemPopup)lines.push(`→ Hệ thống: ${oneLine(c.systemPopup.title,'Tiêu đề hệ thống')} | ${oneLine(c.systemPopup.text,'Thông báo hệ thống')}`);
 return lines;
}
function render(game,ticket){const scope=branchScope(game,ticket.root),names=new Map(scope.ids.map((id,i)=>[id,String(i+1)])),labels=Object.fromEntries((game.meta.statsConfig||[]).map(s=>[s.key,s.label||s.key]));
 const lines=[`MÃ NHÁNH: ${ticket.id}`,`# ${ticket.name}`,'', '> Có thể viết lại toàn bộ: thêm/bớt cảnh, đổi đáp án, điểm và đường đi. Giữ duy nhất dòng MÃ NHÁNH để nhập đúng nhánh. Cảnh đầu tiên là điểm vào; mỗi đáp án cần có dòng → Đến cảnh hoặc → Kết thúc. Không đổi tên chỉ số toàn game.',''];
 const source=game.nodes[ticket.root.sceneId];lines.push('> Bối cảnh trước nhánh (tham khảo):',...(source.text||'').split('\n').map(s=>'> '+s),'> Đáp án mở nhánh: '+source.choices[ticket.root.choiceIndex].text,'');
 for(const id of scope.ids){const n=game.nodes[id];assertSupported(n,id);if((n.choices||[]).length>26)throw new Error(`Cảnh ${id} có quá 26 đáp án.`);
 lines.push(n.isEnding?`## KẾT THÚC E${names.get(id)}${n.speaker?' — '+oneLine(n.speaker,'Tên kết thúc'):''} [${n.endingType||'NORMAL_END'}]`:`## CẢNH ${names.get(id)}${n.speaker?' — '+oneLine(n.speaker,'Người nói'):''}`,n.text||'','');
 if(n.bgImage)lines.push(`→ Ảnh: ${n.bgImage}`);if(n.npcAvatar)lines.push(`→ Ảnh nhân vật: ${n.npcAvatar}`);if(n.systemPopup)lines.push(...effects({systemPopup:n.systemPopup},labels));if(n.automaticEnding)lines.push('→ Tự xét kết thúc');
 for(const [i,c] of (n.choices||[]).entries()){lines.push(`${String.fromCharCode(65+i)} — ${c.text||''}`,...effects(c,labels));if(c.targetNodeId===ticket.root.sceneId)lines.push('→ Về cảnh nguồn');else if(names.has(c.targetNodeId))lines.push(`→ ${game.nodes[c.targetNodeId].isEnding?'Kết thúc E':'Đến cảnh '}${names.get(c.targetNodeId)}`);else throw new Error(`Cảnh ${id} có đáp án chưa nối hoặc đích ngoài nhánh.`);lines.push('');}
 }
 return lines.join('\n');}
export async function exportReplacement(game,root){const scope=branchScope(game,root);if(scope.missing.length)throw new Error('Nhánh còn đích thiếu. Hãy nối đủ trước khi xuất.');const c=game.nodes[root.sceneId].choices[root.choiceIndex];if(c.diceRoll)throw new Error('Chọn đáp án thường để viết lại cả nhánh; chưa hỗ trợ đầu vào xúc xắc.');const ticket={id:crypto.randomUUID(),root:clone(root),name:c.npcCard?.name||c.text||'Nhánh truyện',fingerprint:await fingerprint(game,root)};const script=render(game,ticket),next=clone(game);next.meta={...next.meta,branchRewriteTickets:{...next.meta?.branchRewriteTickets,[ticket.id]:ticket}};return {game:next,script,ticket,scope};}

// Strict parser for the existing author-facing CẢNH / A — / → grammar.
// Unlike full-game import it never repairs, drops or guesses a missing edge.
export function parseReplacement(script,game){const lines=script.replace(/\r\n/g,'\n').split('\n'),nodes={},order=[],stats=game.meta?.statsConfig||[],statMap=new Map();for(const sc of stats)for(const name of [sc.key,sc.label])if(name){const k=slug(name);if(statMap.has(k)&&statMap.get(k)!==sc.key)throw new Error(`Tên chỉ số không rõ ràng: ${name}`);statMap.set(k,sc.key);}
 function stat(label){const key=statMap.get(slug(label));if(!key)throw new Error(`Chỉ số "${label}" chưa có trong game. Hãy dùng đúng tên chỉ số hiện có.`);return key;}
 function assign(target,field,key,value){const map=target[field]||={};if(Object.hasOwn(map,key))throw new Error(`Lặp luật ${key} trên cùng một đáp án. Hãy gộp thành một dòng.`);map[key]=value;}
 let node=null,choice=null,choiceEffects=false;
 for(let index=0;index<lines.length;index++){const raw=lines[index],line=raw.trim(),norm=line.replace(/^#{1,6}\s*/,'').replace(/^\*\*|\*\*$/g,'').trim();if(!line) {if(node&&!choice)node.text+='\n';else if(choice&&!choiceEffects)choice.text+='\n';continue;}let m;
 if((m=norm.match(/^CẢNH\s+([\w]+)(?:\s*[—–:-]\s*(.*))?$/i))){const id='s_'+m[1];if(nodes[id])throw new Error(`Trùng cảnh ${m[1]}.`);node={id,text:'',speaker:m[2]||'',choices:[]};nodes[id]=node;order.push(id);choice=null;continue;}
 if((m=norm.match(/^KẾT THÚC\s+([\w]+)(?:\s*[—–:-]\s*(.*?))?\s*\[(TRUE_END|GOOD_END|NORMAL_END|BAD_END)\]$/i))){const id='e_'+m[1];if(nodes[id])throw new Error(`Trùng kết thúc ${m[1]}.`);node={id,text:'',speaker:m[2]||'',isEnding:true,endingType:m[3].toUpperCase(),choices:[]};nodes[id]=node;order.push(id);choice=null;continue;}
 if(/^#{1,6}\s*(CẢNH|KẾT THÚC)\s/i.test(line)||/^(?:CẢNH\s+\d|KẾT THÚC\s+\S+\s*\[)/i.test(norm))throw new Error(`Dòng ${index+1}: tiêu đề cảnh/kết thúc sai định dạng.`);
 if(!node){if(/^MÃ NHÁNH:|^>|^#|^NHÂN VẬT\s|^$/.test(line))continue;throw new Error(`Dòng ${index+1}: nội dung phải bắt đầu bằng CẢNH hoặc KẾT THÚC.`);}
 if((m=norm.match(/^([A-Z])\s*[—–:.)-]\s*(.+)$/))){if(node.isEnding)throw new Error('Kết thúc không được có đáp án.');if(node.choices.some(c=>c.letter===m[1]))throw new Error(`Trùng đáp án ${m[1]} ở ${node.id}.`);choice={text:m[2],letter:m[1],statModifiers:{},statRequirements:{}};node.choices.push(choice);choiceEffects=false;continue;}
 if((m=norm.match(/^(?:→|->|=>)\s*(.+)$/))){const eff=m[1];let a;if(choice)choiceEffects=true;
 if((a=eff.match(/^Ảnh:\s*(.+)$/i))&&!choice){node.bgImage=a[1];continue;}if((a=eff.match(/^Ảnh nhân vật:\s*(.+)$/i))&&!choice){node.npcAvatar=a[1];continue;}
 if((a=eff.match(/^Hệ thống:\s*([^|]+)\|([\s\S]*)$/i))){(choice||node).systemPopup={title:a[1].trim(),text:a[2].trim()};continue;}
 if(/^Tự xét kết thúc$/i.test(eff)&&!choice){node.automaticEnding=true;continue;}
 if(!choice)throw new Error(`Dòng ${index+1}: hiệu ứng cần đặt dưới đáp án.`);
 if((a=eff.match(/^Đến cảnh\s+([\w]+)$/i))||(a=eff.match(/^Kết thúc\s+([\w]+)$/i))||/^Về cảnh nguồn$/i.test(eff)){if(choice.targetNodeId)throw new Error(`Dòng ${index+1}: một đáp án có nhiều đích.`);choice.targetNodeId=/^Về/i.test(eff)?'@source':/^Đến/i.test(eff)?'s_'+a[1]:'e_'+a[1];continue;}
 if((a=eff.match(/^Cần\s+(.+?)\s*(>=|<=|≥|≤)\s*(-?\d+(?:\.\d+)?)$/i))){const field=['<=','≤'].includes(a[2])?'statRequirementsMax':'statRequirements';assign(choice,field,stat(a[1]),Number(a[3]));continue;}
 if(!eff.includes(':')&&(a=eff.match(/^(.+?)\s+([+-]\d+(?:\.\d+)?)$/))){assign(choice,'statModifiers',stat(a[1]),Number(a[2]));continue;}
 const fields={'cần cờ':'requiresFlag','cần không có cờ':'requiresFlagAbsent','vật phẩm':'grantItem','cần vật phẩm':'requiresItem','mất vật phẩm':'removeItem','kỹ năng':'unlockSkill','hoàn thành nhiệm vụ':'completeQuestId','nhãn đáp án':'label'};
 if((a=eff.match(/^([^:]+):\s*(.+)$/))){const key=a[1].toLowerCase();if(fields[key]){choice[fields[key]]=a[2];continue;}if(key==='cờ'){(choice.grantFlags||=[]).push(a[2]);choice.grantFlag||=a[2];continue;}
 const affinity={'hảo cảm':'npcAffinity','cần hảo cảm':'requiresNpcAffinity','cần hảo cảm tối đa':'requiresNpcAffinityMax'};if(affinity[key]){const parts=a[2].split('|');if(parts.length!==2||!parts[1].trim()||!Number.isFinite(Number(parts[1])))throw new Error('Hảo cảm phải ghi: tên nhân vật | số điểm.');(choice[affinity[key]]||={})[parts[0].trim()]=Number(parts[1]);continue;}
 if(['kinh nghiệm','điểm hệ thống'].includes(key)&&Number.isFinite(Number(a[2]))){choice[key==='kinh nghiệm'?'exp':'systemPoints']=Number(a[2]);continue;}}
 throw new Error(`Dòng ${index+1}: không hiểu "→ ${eff}". Chưa nhập để tránh mất luật.`);
 }
 if(choice){if(choiceEffects)throw new Error(`Dòng ${index+1}: lời truyện sau hiệu ứng chưa có cảnh riêng. Hãy tạo CẢNH hệ quả và nối tới đó.`);choice.text+='\n'+norm;continue;}
 node.text+=raw+'\n';
 }
 if(!order.length)throw new Error('Chưa tìm thấy cảnh nào. Dùng tiêu đề CẢNH 1 hoặc KẾT THÚC E1 [GOOD_END].');
 for(const n of Object.values(nodes)){n.text=n.text.trim();if(!n.text&&!n.automaticEnding)throw new Error(`Cảnh ${n.id} chưa có nội dung.`);if(!n.isEnding&&!n.choices.length)throw new Error(`Cảnh ${n.id} chưa có đáp án đi tiếp hoặc chưa khai là kết thúc.`);for(const c of n.choices){delete c.letter;c.text=c.text.trim();if(!c.targetNodeId||c.targetNodeId!=='@source'&&!nodes[c.targetNodeId])throw new Error(`Đáp án "${c.text}" ở ${n.id} có đích thiếu.`);}}
 const seen=new Set(),queue=[order[0]];for(let i=0;i<queue.length;i++){const id=queue[i];if(id==='@source'||seen.has(id))continue;seen.add(id);queue.push(...nodes[id].choices.map(c=>c.targetNodeId));}if(seen.size!==order.length)throw new Error('Có cảnh không tới được từ cảnh đầu tiên. Hãy nối đủ hoặc bỏ cảnh thừa.');
 for(const n of Object.values(nodes)){if(n.automaticEnding)validateAutomaticEnding(nodes,n);for(const c of n.choices)for(const field of ['statModifiers','statRequirements','statRequirementsMax','npcAffinity','requiresNpcAffinity','requiresNpcAffinityMax'])for(const value of Object.values(c[field]||{}))if(!Number.isFinite(value))throw new Error('Điểm phải là số hữu hạn.');}
 return {nodes,entry:order[0]};}
export async function reviewReplacement(game,text){text=text.trim().replace(/^```(?:markdown|md|text)?\s*\n([\s\S]*?)\n```$/,'$1');const codes=[...text.matchAll(/^MÃ NHÁNH:\s*([a-f0-9-]+)\s*$/gm)];if(codes.length!==1)throw new Error('Cần giữ đúng một dòng MÃ NHÁNH từ bản xuất để nhận diện nhánh.');const ticket=game.meta?.branchRewriteTickets?.[codes[0][1]];if(!ticket)throw new Error('Không tìm thấy mã nhánh trong game này. Hãy xuất lại từ đúng game.');if(ticket.fingerprint!==await fingerprint(game,ticket.root))throw new Error('Nhánh hoặc đường vào đã thay đổi sau khi xuất. Hãy xuất lại để tránh thay nhầm.');const parsed=parseReplacement(text.replace(/\r\n/g,'\n'),game),scope=branchScope(game,ticket.root);return {ticket,parsed,remove:scope.ids.filter(id=>!scope.shared.includes(id)),preserve:scope.shared,newCount:Object.keys(parsed.nodes).length};}
export async function applyReplacement(game,text){const review=await reviewReplacement(game,text),next=clone(game),prefix='branch_'+crypto.randomUUID().replaceAll('-','')+'_',mapping=new Map(Object.keys(review.parsed.nodes).map((id,i)=>[id,prefix+i]));for(const id of review.remove)delete next.nodes[id];for(const [id,n] of Object.entries(review.parsed.nodes)){const node=clone(n);node.id=mapping.get(id);for(const c of node.choices)c.targetNodeId=c.targetNodeId==='@source'?review.ticket.root.sceneId:mapping.get(c.targetNodeId);next.nodes[node.id]=node;}next.nodes[review.ticket.root.sceneId].choices[review.ticket.root.choiceIndex].targetNodeId=mapping.get(review.parsed.entry);delete next.meta.branchRewriteTickets[review.ticket.id];next.meta.sourceScriptOutdated=!!next.meta.sourceScript;return {game:next,review};}
