import React,{useRef,useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {branchScope} from '@/lib/gameStudio/branchExchange';
import {exportReplacement,reviewReplacement,applyReplacement} from '@/lib/gameStudio/branchReplacement';
import {sceneLabel} from '@/lib/gameStudio/mindMap';

export default function BranchExchangeDialog({game,initialRoot,onApply,onClose}) {
  const [root,setRoot]=useState(initialRoot||{sceneId:Object.keys(game.nodes).find(id=>game.nodes[id].choices?.length)||'',choiceIndex:0});
  const [text,setText]=useState(''),[review,setReview]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  const latest=useRef(game);latest.current=game;
  let scope,scopeError='';try{scope=branchScope(game,root);}catch(e){scopeError=e.message;}
  async function run(fn){setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
  function download(){const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='kich-ban-nhanh.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  return <Dialog open onOpenChange={open=>!open&&onClose()}><DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Viết lại toàn bộ một nhánh</DialogTitle><DialogDescription>Xuất kịch bản thông thường để viết lại tự do: thêm/bớt cảnh, thay đáp án, điểm và bố cục. Khi nhập, thay cả nhánh bằng sơ đồ mới, không ghép từng ô cũ.</DialogDescription></DialogHeader>
    <label className="text-sm">Chọn cảnh có đáp án mở nhánh<select disabled={busy} className="block border rounded p-2 w-full bg-background" value={root.sceneId} onChange={e=>setRoot({sceneId:e.target.value,choiceIndex:0})}>{Object.entries(game.nodes).filter(([,n])=>n.choices?.length).map(([id,n])=><option key={id} value={id}>{sceneLabel(id,n)}</option>)}</select></label>
    <label className="text-sm">Nhánh cần xuất<select disabled={busy} className="block border rounded p-2 w-full bg-background" value={root.choiceIndex} onChange={e=>setRoot({...root,choiceIndex:Number(e.target.value)})}>{(game.nodes[root.sceneId]?.choices||[]).map((c,i)=><option key={i} value={i}>{c.npcCard?.name||`${String.fromCharCode(65+i)} · ${c.text||'Chưa viết'}`}</option>)}</select></label>
    <p className="text-sm">{scope?`${scope.ids.length} cảnh trong nhánh · ${scope.shared.length} cảnh dùng chung sẽ được giữ lại cho các nhánh khác.`:scopeError}</p>
    <div className="flex flex-wrap gap-2"><Button disabled={busy||!scope} onClick={()=>run(async()=>{const base=latest.current,result=await exportReplacement(base,root);if(latest.current!==base)throw new Error('Game vừa thay đổi. Hãy xuất lại.');onApply(result.game);setText(result.script);setReview(null);setNotice('Đã xuất kịch bản và lưu mã nhận diện vào game. Chỉ giữ dòng MÃ NHÁNH; phần kịch bản có thể viết lại hoàn toàn.');})}>Xuất kịch bản nhánh</Button><Button variant="outline" disabled={busy||!text} onClick={()=>run(async()=>{await navigator.clipboard.writeText(text);setNotice('Đã sao chép kịch bản để gửi AI.');})}>Sao chép</Button><Button variant="outline" disabled={busy||!text} onClick={download}>Tải kịch bản (.md)</Button></div>
    <p className="text-sm text-muted-foreground">Không cần giữ cảnh hay đáp án cũ. Chỉ giữ dòng MÃ NHÁNH để nhận diện nơi nhập. Dùng CẢNH 1, A — lời đáp án, → Đến cảnh 2, hoặc → Kết thúc HE và KẾT THÚC HE [GOOD_END]. Cảnh đầu tiên là điểm vào mới. Điểm dùng tên chỉ số đang có trong game. Muốn quay ra cảnh trước nhánh: → Về cảnh nguồn.</p>
    <label className="text-sm">Kịch bản / Dán toàn bộ nhánh đã viết lại<Textarea aria-label="Kịch bản nhánh viết lại" disabled={busy} rows={14} className="text-sm leading-7 mt-2" value={text} onChange={e=>{setText(e.target.value);setReview(null);}} placeholder="MÃ NHÁNH: giữ dòng này từ bản xuất&#10;&#10;CẢNH 1 — Mở đầu mới&#10;Nội dung mới…&#10;&#10;A — Lựa chọn mới&#10;→ Đến cảnh 2"/></label>
    <Button disabled={busy||!text.trim()} onClick={()=>run(async()=>{setReview(null);setReview(await reviewReplacement(latest.current,text));})}>{busy?'Đang xử lý…':'Kiểm tra và nhận diện nhánh'}</Button>
    {review&&<div className="space-y-3 border rounded p-3"><strong>Nhập vào nhánh: {review.ticket.name}</strong><p className="text-sm">Gỡ {review.remove.length} cảnh cũ riêng của nhánh → tạo {review.newCount} cảnh mới. Giữ nguyên {review.preserve.length} cảnh dùng chung và tất cả nhánh khác. Chỉ đổi đích của đáp án mở nhánh; giữ điểm, điều kiện và thẻ nhân vật của đáp án đó.</p><p className="text-sm text-amber-700">Đây là thay toàn bộ nhánh. Tiến trình chơi cũ đang ở cảnh bị thay có thể không tiếp tục được; cần chơi lại. Hãy xem nội dung và đường nối mới bên dưới trước khi áp dụng.</p><div className="max-h-64 overflow-auto space-y-2">{Object.values(review.parsed.nodes).map(n=><details className="border rounded p-2" key={n.id}><summary>{n.isEnding?'Kết thúc':'Cảnh'} {n.id.slice(2)}{n.speaker?' · '+n.speaker:''}</summary><p className="text-sm whitespace-pre-wrap">{n.text}</p>{n.choices.map((c,i)=><p className="text-sm mt-2" key={i}>{String.fromCharCode(65+i)} — {c.text}<br/>→ {c.targetNodeId==='@source'?'Về cảnh nguồn':c.targetNodeId.startsWith('e_')?'Kết thúc '+c.targetNodeId.slice(2):'Cảnh '+c.targetNodeId.slice(2)}</p>)}</details>)}</div><Button disabled={busy} onClick={()=>run(async()=>{const base=latest.current;const result=await applyReplacement(base,text);if(latest.current!==base)throw new Error('Game vừa thay đổi. Hãy kiểm tra lại.');onApply(result.game);setReview(null);setNotice(`Đã thay nhánh ${result.review.ticket.name} bằng ${result.review.newCount} cảnh mới. Hãy chạy QA và chơi thử. Muốn sửa tiếp, xuất lại nhánh để lấy mã mới.`);})}>Thay nhánh này bằng kịch bản mới</Button></div>}
    {error&&<p role="alert" className="text-sm text-red-600">{error}</p>}{notice&&<p role="status" className="text-sm">{notice}</p>}
  </DialogContent></Dialog>;
}
