import React,{useMemo,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {aiCall} from '@/lib/aiCall';
import {BLUEPRINT_SCHEMA,applyBlueprint,makeSkeletonPlan,normalizeBlueprintIds,normalizeBlueprintConnections,normalizeBlueprintEntry,normalizeBlueprintSemantics,verifyUnsupportedClaims,enforceExplicitBlueprintRules,validateBlueprintAgainstRequest,blueprintPrompt} from '@/lib/gameStudio/graphBlueprint';
import {buildMindMap,sceneLabel} from '@/lib/gameStudio/mindMap';
import ScriptImportPanel from './ScriptImportPanel';
const cls='block w-full border rounded p-2 bg-background';
function Preview({result}){
 const nodes=Object.fromEntries(result.ids.map(id=>[id,result.game.nodes[id]]));
 for(const id of result.ids)for(const c of nodes[id].choices||[]){const target=c.targetNodeId;if(target&&!nodes[target]&&result.game.nodes[target])nodes[target]={...result.game.nodes[target],choices:[],combat:undefined,workshopPosition:undefined};}
 const graph=buildMindMap(nodes);
 return <div className="overflow-auto border rounded" style={{height:260}}><svg width={Math.max(600,graph.width*.45)} height={graph.height*.45} aria-label="Xem trước các ô mới"><g transform="scale(.45)">{graph.edges.map((e,i)=>{const a=graph.cards.find(c=>c.key===e.from),b=graph.cards.find(c=>c.key===e.to);return <line key={i} x1={a.x+310} y1={a.y+40} x2={b.x} y2={b.y+40} stroke="#8b5cf6" strokeWidth="3"/>;})}{graph.cards.map(c=><g key={c.key}><rect x={c.x} y={c.y} width="310" height="95" rx="10" fill={c.kind==='ending'?'#dcfce7':c.kind==='choice'?'#fef3c7':'#ede9fe'} stroke="#8b5cf6"/><text x={c.x+10} y={c.y+30} fontSize="18" fill="#111827">{c.title.slice(0,30)}</text><text x={c.x+10} y={c.y+65} fontSize="14" fill="#475569">{c.sceneId}</text></g>)}</g></svg></div>;
}
export default function GraphBlueprintDialog({game,onApply,onClose}){
 const [mode,setMode]=useState('manual'),[count,setCount]=useState(5),[choices,setChoices]=useState(4),[kind,setKind]=useState('linear'),[effects,setEffects]=useState(false),[source,setSource]=useState('');
 const [request,setRequest]=useState(''),[plan,setPlan]=useState(null),[snapshot,setSnapshot]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [budget,setBudget]=useState(1),[calls,setCalls]=useState(0);
 const latest=useRef(game);latest.current=game;
 const mounted=useRef(true);React.useEffect(()=>{mounted.current=true;return ()=>{mounted.current=false;};},[]);
 React.useEffect(()=>{if(!plan)return;const userRequest=mode==='ai'?request:'';const checked=normalizeBlueprintSemantics(enforceExplicitBlueprintRules(verifyUnsupportedClaims(normalizeBlueprintEntry(game,normalizeBlueprintConnections(game,normalizeBlueprintIds(game,plan)),userRequest),userRequest),userRequest),userRequest);if(JSON.stringify(checked)!==JSON.stringify(plan))setPlan(checked);},[game,mode,plan,request]);
 const review=useMemo(()=>{if(!plan)return null;try{const result=applyBlueprint(game,plan),warnings=mode==='ai'?validateBlueprintAgainstRequest(plan,request):[];return {result,error:'',warnings};}catch(e){return {result:null,error:e.message,warnings:[]};}},[game,mode,plan,request]);
 async function propose(){
  setError('');setPlan(null);setCalls(0);const original=latest.current;const stamp=JSON.stringify(original);setSnapshot(stamp);let used=0;
  try{
   let next;
   if(mode==='manual'){
    next=makeSkeletonPlan({count,choices,consequences:effects,kind});
    if(source){const n=original.nodes[source];if(n.isEnding||n.combat||n.choices?.some(c=>c.diceRoll))throw new Error('Hãy nối riêng các kết quả xúc xắc/chiến đấu bằng kéo chuột.');next.connections=n.choices?.length?n.choices.map((_,i)=>({sourceId:source,choiceIndex:i,target:next.nodes[0].id})):[{sourceId:source,choiceIndex:-1,target:next.nodes[0].id}];}
   }else{
    if(!request.trim())throw new Error('Hãy nhập yêu cầu muốn AI thiết kế.');
    setBusy(true);let correction='';
    for(let attempt=0;attempt<budget;attempt++){
     next=await aiCall(`${blueprintPrompt(original,request)}${correction}`,{jsonSchema:BLUEPRINT_SCHEMA,useCache:false,maxAttempts:1,maxOutputTokens:32768,onRequest:()=>{if(!mounted.current||used>=budget)throw new Error('Đã dừng theo ngân sách.');used++;setCalls(used);}});
     next=normalizeBlueprintSemantics(enforceExplicitBlueprintRules(verifyUnsupportedClaims(normalizeBlueprintEntry(original,normalizeBlueprintConnections(original,normalizeBlueprintIds(original,next)),request),request),request),request);
     const semanticErrors=validateBlueprintAgainstRequest(next,request);if(!semanticErrors.length)break;
     correction=`\n\n# LẦN TRƯỚC KHÔNG ĐẠT — PHẢI TRẢ LẠI TOÀN BỘ JSON ĐÃ SỬA\n${semanticErrors.join('\n')}\nKhông giải thích; không trả bản vá rời; trả toàn bộ nodes/connections hoàn chỉnh.`;
    }
   }
   if(!mounted.current)return;if(stamp!==JSON.stringify(latest.current))throw new Error('Sơ đồ đã thay đổi trong lúc thiết kế. Hãy tạo lại bản xem trước.');const userRequest=mode==='ai'?request:'';setPlan(normalizeBlueprintSemantics(enforceExplicitBlueprintRules(verifyUnsupportedClaims(normalizeBlueprintEntry(original,normalizeBlueprintConnections(original,normalizeBlueprintIds(original,next)),userRequest),userRequest),userRequest),userRequest));
  }catch(e){if(mounted.current)setError(e.message);}finally{if(mounted.current)setBusy(false);}
 }
 return <Dialog open onOpenChange={v=>!v&&!busy&&onClose()}><DialogContent className="max-w-4xl max-h-[92vh] overflow-y-auto"><DialogHeader><DialogTitle>Dựng sơ đồ & AI thiết kế</DialogTitle><DialogDescription>Tạo bản xem trước trước khi thêm ô hoặc đổi đường nối. Không xóa các cảnh hiện tại.</DialogDescription></DialogHeader>
 <fieldset disabled={busy} className="space-y-3"><div className="flex flex-wrap gap-2"><Button variant={mode==='manual'?'default':'outline'} onClick={()=>{setMode('manual');setPlan(null);setError('');setCalls(0);}}>Dựng khung theo số lượng</Button><Button variant={mode==='ai'?'default':'outline'} onClick={()=>{setMode('ai');setPlan(null);setError('');setCalls(0);}}>AI thiết kế theo yêu cầu</Button><Button variant={mode==='import'?'default':'outline'} onClick={()=>{setMode('import');setPlan(null);setError('');setCalls(0);}}>Nhập kịch bản · Tiết kiệm AI</Button></div>
 {mode==='import'?null:<>
 {mode==='manual'?<><label>Kiểu sơ đồ<select className={cls} value={kind} onChange={e=>{setKind(e.target.value);setPlan(null);}}><option value="linear">Các đáp án hội tụ về cảnh kế tiếp</option><option value="parallel">Tách thành các tuyến song song</option></select></label><div className="grid grid-cols-2 gap-3"><label>{kind==='parallel'?'Số cảnh chính mỗi tuyến':'Số cảnh chính'}<input className={cls} type="number" min={1} max={30} value={count} onChange={e=>{setCount(Number(e.target.value));setPlan(null);}}/></label><label>Số đáp án mỗi cảnh<input className={cls} type="number" min={1} max={12} value={choices} onChange={e=>{setChoices(Number(e.target.value));setPlan(null);}}/></label></div><label className="flex gap-2"><input type="checkbox" checked={effects} onChange={e=>{setEffects(e.target.checked);setPlan(null);}}/>Mỗi đáp án có một cảnh hệ quả riêng trước khi đi tiếp</label>{kind==='parallel'&&<p className="text-xs">Thêm một cảnh tách tuyến; mỗi đáp án mở một tuyến có số cảnh đã chọn. Các cảnh trong mỗi tuyến hội tụ về cảnh kế. Không tạo cây phân nhánh vô hạn.</p>}<label>Nối khung mới từ<select className={cls} value={source} onChange={e=>{setSource(e.target.value);setPlan(null);}}><option value="">Đặt riêng — tôi nối bằng chuột sau</option>{Object.entries(game.nodes).filter(([,n])=>!n.isEnding).map(([id,n])=><option key={id} value={id}>{sceneLabel(id,n)}</option>)}</select></label>{source&&<p className="text-amber-700 text-sm">Toàn bộ đáp án thường của cảnh nguồn sẽ đổi đích sang đầu khung mới. Các cảnh cũ vẫn được giữ.</p>}<p className="text-xs">Cuối khung để trống đích để bạn chọn ending. Tối đa 300 ô mới/lần, bao gồm hệ quả.</p></>:<><label>Yêu cầu của bạn<textarea className={cls} rows={5} value={request} onChange={e=>{setRequest(e.target.value);setPlan(null);}} placeholder="Ví dụ: Đây là cung đấu. Sủng ái ban đầu 50, dưới 10 thì thua. Viết lời báo bị đày lãnh cung. Tạo 4 ending theo sủng ái, nối các đáp án Cảnh 60 vào ô xét kết thúc ẩn. Giữ nguyên các cảnh khác."/></label><p className="text-xs">Dùng cấu hình AI hiện có. AI được đề xuất ô, đường nối, điểm, cờ/vật phẩm, ngưỡng thua dưới và lời kết. Luật chưa được engine hỗ trợ sẽ được báo rõ; không tự áp bản thiết kế thiếu luật.</p></>}
 {mode==='ai'&&<label className="block text-sm">Ngân sách tạo sơ đồ<select className={cls} value={budget} onChange={e=>setBudget(Number(e.target.value))}><option value={1}>1 lượt · sửa cấu trúc trên máy (khuyên dùng)</option><option value={2}>Tối đa 2 lượt nếu AI thiếu dữ liệu</option></select><span className="text-xs">Hệ thống giữ kết quả hợp lệ và tự sửa ID, vai trò nhánh, đường mở đầu, cờ và kiểm tra cân bằng trên máy; không gọi lại chỉ vì lời văn còn ngắn.</span></label>}
 <Button onClick={propose}>{mode==='ai'?'AI tạo bản thiết kế':'Xem trước khung'}</Button></>}
 </fieldset>
 {mode==='import'&&<ScriptImportPanel game={game} onApply={onApply} onClose={onClose} Preview={Preview} onBusyChange={setBusy}/>}
 {mode!=='import'&&(busy||calls>0)&&<p role="status">{busy?'AI đang thiết kế · ':''}Đã gọi {calls}/{budget} lượt, chưa thay đổi game.</p>}{error&&<p role="alert" className="text-red-600">{error}</p>}
 {plan&&<div className="border rounded-lg p-3 space-y-3"><h3 className="font-semibold">Bản đề xuất — chưa áp dụng</h3><p className="whitespace-pre-wrap text-sm">{typeof plan.summary==='string'?plan.summary:''}</p>{review?.error&&<p role="alert" className="text-red-600">{review.error}</p>}{review?.warnings?.length>0&&<div role="status" className="text-amber-700"><p className="font-medium">Bản tạm còn thiếu, nhưng có thể áp dụng ngay và bổ sung sau:</p><p>{review.warnings.join(' ')}</p></div>}{review?.result&&<><p>{review.result.ids.length} ô mới · {plan.connections.length} đường nguồn thay đổi · {plan.stats.length} chỉ số thêm/sửa</p><Preview result={review.result}/><details><summary>Nội dung và điều kiện từng ô mới</summary><div className="space-y-2 max-h-80 overflow-auto">{plan.nodes.map(n=><details key={n.id} className="border rounded p-2"><summary>{n.title || n.id} · {n.role === 'ending' ? 'Kết thúc' : n.role === 'router' ? 'Xét kết thúc ẩn' : 'Cảnh'}</summary><p className="text-sm whitespace-pre-wrap">{n.text || 'Chưa viết nội dung'}</p>{n.choices.map((c,i)=><div key={i} className="text-xs border-t mt-2 pt-2"><p>{i+1}. {c.text || 'Chưa viết đáp án'} → {plan.nodes.find(other=>other.id===c.target)?.title || (game.nodes[c.target] ? sceneLabel(c.target,game.nodes[c.target]) : c.target || 'Chưa nối')}</p>{c.min.map(b=><p key={b.key}>{b.key} ≥ {b.value}</p>)}{c.max.map(b=><p key={b.key}>{b.key} ≤ {b.value}</p>)}{c.modifiers.map(b=><p key={b.key}>{b.key}: {b.value>=0?'+':''}{b.value}</p>)}{[['requiresFlag','Cần cờ'],['requiresFlagAbsent','Chưa có cờ'],['requiresItem','Cần vật phẩm'],['grantFlag','Nhận cờ'],['grantItem','Nhận vật phẩm']].map(([key,label])=>c[key]&&<p key={key}>{label}: {c[key]}</p>)}</div>)}</details>)}</div></details>{plan.connections.length>0&&<details open><summary>Đường nối sẽ đổi</summary>{plan.connections.map((c,i)=><p key={i} className="text-sm">{c.sourceId} · {c.choiceIndex===-1?'Đáp án đầu':`Đáp án ${c.choiceIndex+1}`} → {c.target}</p>)}</details>}{plan.stats.map(s=><p className="text-sm" key={s.key}>{s.label} ({s.key}): ban đầu {s.initial}; {s.isVital?`thua khi ≤ ${s.deathThreshold}`:'không sinh tồn'}</p>)}{(plan.gameOverTitle||plan.gameOverText)&&<p className="text-sm">Lời báo thua: {plan.gameOverTitle} — {plan.gameOverText}</p>}<Button onClick={()=>{if(snapshot!==JSON.stringify(game)){setError('Dữ liệu đã thay đổi. Hãy tạo lại bản xem trước.');return;}onApply(review.result);onClose();}}>{review.warnings?.length?'Áp dụng bản tạm và bổ sung sau':'Áp dụng bản thiết kế này'}</Button></>}</div>}
 </DialogContent></Dialog>;
}
