import {scenes, demoStats} from './cinematicDemo.js';
const stat=(key,label,initial)=>({key,label,initial});
const choice=(text,modifiers,systemText='')=>({text,modifiers,systemText});
const scene=(title,place,time,paragraphs,quote,choices)=>({title,place,time,paragraphs,quote,choices});
const end=(label,title,text,quote,min)=>({label,title,paragraphs:[text],quote,min});
export const genreDemos = {
 cinema:{id:'cinema',label:'Điện ảnh · Tình cảm',title:'Chuyện dưới hiên hoa',description:'Hình và lời thoại, khoảng lặng và cảm xúc.',art:'/hero-transmigration.jpg',stats:demoStats.slice(0,2),scenes,score:'favor',endings:[
  end('Lời hẹn','Hẹn người khi hoa nở','Nàng nhận lại bức thư, ánh mắt đã bớt dè chừng. Trước khi bạn rời đi, nàng đặt một cánh hoa vào trang sách đang đọc.','Ngày mai, vẫn giờ này nhé.',35),
  end('Chưa nói thành lời','Trang sách khép lại','Nàng cất bức thư vào tay áo. Giữa hai người còn những điều chưa thể nói ra. Ngoài hiên, nắng đã tắt.','Hôm khác… ta sẽ kể người nghe.',-Infinity)]},
 storybook:{id:'storybook',label:'Trang sách · Cổ tích',title:'Người giữ mùa xuân',description:'Trang giấy sáng, chữ là trung tâm; lời kết như trang cuối cuốn sách.',art:'/hero-transmigration.jpg',stats:[stat('kindness','Lòng nhân hậu',0),stat('courage','Can đảm',2)],score:'kindness',scenes:[
  scene('Lá thư của khu rừng','Bìa rừng','Trang thứ nhất',['Chiếc hộp thư trong thân cây đã im lặng suốt mùa đông. Sáng nay, một lá thư màu xanh nằm bên trong, không có tên người gửi.','Dưới gốc cây, một chú chim với đôi cánh ướt đang cố kéo sợi dây buộc lá thư.'], 'Xin hãy mang mùa xuân trở lại.',[choice('Ủ ấm chú chim rồi cùng mở lá thư.',{kindness:4}),choice('Mang lá thư đi, để chú chim tự tìm chỗ trú.',{kindness:-2}),choice('Đợi đôi cánh khô rồi hỏi đường vào rừng.',{kindness:2,courage:1})]),
  scene('Hạt giống cuối cùng','Giếng cổ','Trang thứ hai',['Dưới đáy giếng cạn là một hạt giống phát sáng. Chú chim nói rằng nó chỉ nảy mầm khi có người tự nguyện dành phần nước cuối cùng của mình.','Bình nước trong tay bạn không còn nhiều. Con đường về làng vẫn còn xa.'],'Mùa xuân có thể bắt đầu từ một điều rất nhỏ.',[choice('Tưới hạt giống, rồi cùng tìm nguồn nước mới.',{kindness:4,courage:2}),choice('Chia đôi nước cho mình và hạt giống.',{kindness:1}),choice('Giữ nước và để hạt giống lại giếng.',{kindness:-4})])],endings:[end('Mùa xuân trở lại','Khi khu rừng thức giấc','Mầm xanh chạm miệng giếng. Suốt con đường về, những chiếc lá non mở ra theo bước chân bạn. Chú chim mang tin mùa xuân đến từng mái nhà.','Một điều nhỏ, một khu rừng lớn.',6),end('Lời hứa còn tiếp','Mầm cây bên cửa sổ','Hạt giống chưa đánh thức cả khu rừng, nhưng một mầm nhỏ đã xanh. Bạn nhận lời quay lại chăm nó vào mỗi buổi sáng.','Câu chuyện này còn một trang chưa viết.',0),end('Mùa đông ở lại','Lá thư không người nhận','Chiếc hộp thư lại khép. Khu rừng chờ thêm một mùa nữa, còn bạn mang theo ký ức về hạt giống chưa nảy mầm.','Có những cánh cửa cần lòng tốt để mở ra.',-Infinity)]},
 system:{id:'system',label:'Hệ thống RPG',title:'Giao thức thức tỉnh',description:'Nhiệm vụ đi cùng cảnh, cửa sổ hệ thống có xác nhận; kết thúc là bản tổng kết nhiệm vụ.',art:'/hero-adventure.jpg',stats:[stat('hp','Sinh lực',40),stat('insight','Dữ liệu giải mã',0),stat('energy','Năng lượng',12)],score:'insight',death:'hp',system:'Kết nối thành công. Nhiệm vụ: thoát khỏi tháp trước khi lõi ngừng hoạt động. Sinh lực về 0 sẽ thất bại.',scenes:[
  scene('Khởi tạo người thức tỉnh','Tầng 01 · Tháp ký ức','Nhiệm vụ 01',['Một khung sáng hiện ra giữa bóng tối. Dãy ký tự lạ trượt qua mắt bạn rồi dừng ở dòng chữ: “Người dùng đã được xác nhận”.','Cánh cửa trước mặt bị khóa. Bên cạnh là bảng điều khiển còn sáng và một khe thông gió hẹp.'],'Chọn cách vượt qua phòng đầu tiên.',[choice('Giải mã bảng điều khiển.',{insight:4,energy:-2},'Đã thu thập 4 mảnh dữ liệu. Cửa tầng hai mở.'),choice('Bò qua khe thông gió.',{hp:-8,insight:1},'Đã vượt phòng. Sinh lực giảm do vết thương.'),choice('Dùng cơ thể phá lõi điện đang quá tải.',{hp:-45},'Cảnh báo: tổn thương vượt ngưỡng sinh tồn.')]),
  scene('Quyền truy cập cuối cùng','Tầng 02 · Lõi tháp','Nhiệm vụ 02',['Lõi tháp đang tự xóa những ký ức lưu bên trong. Trên bảng điều khiển chỉ còn hai đường truyền hoạt động.','Bạn có thể mang dữ liệu theo mình, hoặc ưu tiên mở cửa thoát trước khi hệ thống tắt.'],'Bạn sẽ giữ lại điều gì?',[choice('Giải mã và sao lưu ký ức trước khi thoát.',{insight:4,energy:-4},'Sao lưu hoàn tất. Đã khôi phục ký ức của tháp.'),choice('Mở cửa thoát, mang theo phần dữ liệu còn đọc được.',{insight:1},'Đã thoát tháp. Dữ liệu chỉ được khôi phục một phần.'),choice('Ngắt mọi kết nối để bảo toàn sinh lực.',{insight:-3},'Mất kết nối với kho ký ức. Đã rời khỏi tháp.')])],endings:[end('Hoàn thành xuất sắc','Ký ức được phục hồi','Bạn bước ra khỏi tháp cùng bản sao ký ức. Những người bị lãng quên đã có lại tên mình. Hệ thống đóng nhiệm vụ và lưu kết quả.','Nhiệm vụ hoàn thành · Dữ liệu nguyên vẹn.',6),end('Hoàn thành một phần','Người trở về','Cánh cửa khép sau lưng bạn. Bạn sống sót, nhưng dữ liệu mang về chỉ đủ để ghép lại một phần câu chuyện của tòa tháp.','Nhiệm vụ kết thúc · Cần phục hồi thêm dữ liệu.',2),end('Nhiệm vụ thất bại','Kết nối đã đóng','Bạn không thể mang ký ức của tòa tháp trở về. Hệ thống ghi nhận lần thử chưa thành công và chờ một lần khởi động mới.','Không còn phiên nhiệm vụ đang hoạt động.',-Infinity)],deathEnding:end('Thua cuộc','Tín hiệu sinh tồn đã mất','Nguồn điện quá tải tràn qua cơ thể. Trước khi cánh cửa kịp mở, giao diện hệ thống chuyển sang màu đỏ và khóa phiên nhiệm vụ.','Sinh lực đã về ngưỡng thất bại.',-Infinity)},
 mystery:{id:'mystery',label:'Bí ẩn · Điều tra',title:'Hồ sơ lúc không giờ',description:'Hồ sơ hẹp, ít trang trí; dấu vết và lời kết kiểu báo cáo điều tra.',art:'/hero-detective.jpg',stats:[stat('evidence','Bằng chứng',0),stat('risk','Rủi ro',0)],score:'evidence',scenes:[
  scene('Căn phòng không có người','Hồ sơ 014 · Khách sạn cũ','00:17',['Cửa phòng đã mở sẵn. Trên bàn là hai tách trà, nhưng lễ tân khẳng định chỉ có một người thuê phòng.','Một bức ảnh úp mặt nằm cạnh cửa sổ. Góc giấy còn ẩm.'],'Đừng tin điều đầu tiên nhìn thấy.',[choice('Chụp lại hiện trường trước khi chạm vào đồ vật.',{evidence:4}),choice('Lật bức ảnh lên ngay.',{evidence:1,risk:2}),choice('Dọn hai tách trà để nhìn rõ mặt bàn.',{evidence:-2,risk:1})]),
  scene('Người trong bức ảnh','Hồ sơ 014 · Phòng lưu trữ','00:43',['Người trong ảnh xuất hiện trong sổ khách với hai cái tên khác nhau. Một dòng ghi chú đã bị xóa, nhưng trang giấy vẫn còn vết hằn.','Ngoài cửa có tiếng bước chân dừng lại. Bạn tắt đèn bàn và chờ.'],'Sự thật cần được giữ nguyên dấu vết.',[choice('Đối chiếu hai bản đăng ký và sao lưu chứng cứ.',{evidence:4}),choice('Mang bức ảnh rời khỏi khách sạn.',{evidence:1}),choice('Xé trang sổ có tên mình rồi bỏ đi.',{evidence:-4,risk:4})])],endings:[end('Hồ sơ khép lại','Hai cái tên, một sự thật','Các bản đăng ký và hình ảnh được đối chiếu thành công. Bạn gửi hồ sơ đầy đủ cho người cần nhận, không bỏ lại khoảng trống để sự thật bị thay thế.','Kết luận: đã xác minh.',6),end('Hồ sơ còn mở','Dấu vết chưa hoàn chỉnh','Bạn giữ được một đầu mối, nhưng chưa đủ chứng cứ để kết luận. Người trong bức ảnh vẫn còn một cái tên chưa được giải thích.','Kết luận: cần điều tra bổ sung.',1),end('Mất dấu','Căn phòng đã được dọn sạch','Khi bạn quay lại, cả bức ảnh lẫn cuốn sổ đều biến mất. Những gì còn nhớ không thể thay thế chứng cứ đã mất.','Kết luận: không thể xác minh.',-Infinity)]},
 palace:{id:'palace',label:'Cung đấu',title:'Dưới rèm châu',description:'Khung nghi lễ, dấu ấn cung đình và lựa chọn đối xứng; lời kết dạng chiếu thư.',art:'/hero-transmigration.jpg',stats:[stat('favor','Sủng ái',30),stat('reputation','Danh vọng',20),stat('risk','Hiềm nghi',0)],score:'favor',scenes:[
  scene('Chén trà trong đại điện','Chiêu Hoa điện','Ngày 12 · Giờ Tỵ',['Hoàng hậu đặt chén trà xuống. Ánh mắt nàng dừng trên người bạn lâu hơn thường lệ. Không ai trong điện dám thở mạnh.','Một phong thư được đặt trước thềm, nét chữ trên bì thư giống hệt nét chữ của bạn.'],'Ngươi có điều gì muốn nói?',[choice('Xin đối chiếu giấy và dấu niêm phong trước khi luận tội.',{favor:5,reputation:3}),choice('Nhận phần sơ suất vì đã để người khác dùng thư phòng.',{favor:1,risk:1}),choice('Lập tức chỉ tội người ngồi bên cạnh.',{favor:-5,risk:4})]),
  scene('Lời chứng sau rèm','Chiêu Hoa điện','Ngày 12 · Giờ Ngọ',['Cung nữ giữ cửa quỳ xuống, nói rằng đã thấy người mang thư đi qua phía tây. Nhưng nàng không dám gọi tên.','Hoàng hậu cho bạn một cơ hội cuối cùng để hỏi lại.'],'Trong điện này, từng lời đều có người ghi nhớ.',[choice('Xin bảo vệ cung nữ để nàng yên tâm làm chứng.',{favor:5,reputation:4}),choice('Xin thêm thời gian tìm người đưa thư.',{favor:1}),choice('Ép cung nữ nhận hết trách nhiệm.',{favor:-6,risk:5})])],endings:[end('Vinh sủng','Một lời chiếu dưới rèm châu','Lời chứng được bảo toàn, bức thư giả tìm thấy chủ nhân. Chiếu ban xuống trong buổi sớm: bạn được khôi phục danh dự và giao quản thư phòng.','Lấy sự sáng suốt mà giữ lòng người.',38),end('Bình an','Đèn vẫn sáng trong cung nhỏ','Vụ việc tạm khép. Không có chiếu thăng vị, cũng không có lời giáng tội. Bạn trở về cung nhỏ, hiểu rằng bình an cũng là điều cần gìn giữ.','Ngày mai, cửa cung vẫn mở.',28),end('Thất sủng','Rèm châu không còn vén','Những lời nóng vội khiến bạn mất sự tin cậy. Lệnh chuyển cung được đưa đến trước khi trời tối. Trong đại điện, không còn ai nhắc tên bạn.','Từ đây, tự giữ lấy mình.',-Infinity)]},
 tycoon:{id:'tycoon',label:'Trọng sinh · Làm giàu',title:'Trở lại năm 1998',description:'Bản ghi quyết định kinh doanh và khoản đầu tư; kết thúc là báo cáo hành trình.',art:'/hero-system.jpg',stats:[stat('capital','Vốn hiện có',12000),stat('credibility','Uy tín',0),stat('assets','Tài sản',0)],score:'credibility',scenes:[
  scene('Mảnh đất cuối con phố','Thương vụ 01','Tháng 3 / 1998',['Góc phố nhỏ này hiện tại chẳng ai để ý. Nhưng bạn nhớ rõ: mười năm nữa, nó sẽ trở thành khu thương mại sầm uất nhất thành phố.','Chủ đất muốn bán nhanh. Trong tay bạn là số vốn đủ cho một lần lựa chọn, không phải mọi cơ hội.'],'Biết trước tương lai không thay thế được việc kiểm tra hiện tại.',[choice('Kiểm tra giấy tờ rồi mua một phần đất phù hợp số vốn.',{capital:-6000,assets:1,credibility:4}),choice('Thuê ngắn hạn để thử mở cửa hàng.',{capital:-2000,credibility:1}),choice('Đặt cọc toàn bộ mà không đọc điều khoản.',{capital:-10000,credibility:-3})]),
  scene('Đối tác đầu tiên','Thương vụ 02','Tháng 6 / 1998',['Một người quen đề nghị hợp tác bán hàng trên con phố. Họ có nguồn hàng, bạn có hiểu biết về nhu cầu sắp tới.','Bản hợp đồng đặt trước mặt chia lợi nhuận rất đẹp, nhưng không nói ai sẽ chịu khoản lỗ đầu tiên.'],'Lợi nhuận chỉ có ý nghĩa khi rủi ro được gọi đúng tên.',[choice('Thống nhất trách nhiệm và thử một lô hàng nhỏ.',{capital:3000,credibility:4}),choice('Tạm hoãn, giữ vốn cho cơ hội khác.',{credibility:1}),choice('Ký ngay và ứng trước phần lớn tiền hàng.',{capital:-2000,credibility:-3})])],endings:[end('Khởi nghiệp vững vàng','Một nền móng cho ngày mai','Những thương vụ nhỏ được ghi chép minh bạch. Bạn chưa sở hữu cả thành phố, nhưng đã có đối tác tin cậy và nền móng để đi xa hơn.','Giá trị đầu tiên tạo ra là sự tin cậy.',6),end('Bảo toàn cơ hội','Vẫn còn một ngày mai','Bạn không thắng lớn, nhưng đã giữ được khả năng lựa chọn. Cuốn sổ kinh doanh còn nhiều trang trống để viết tiếp.','Giữ được cơ hội cũng là một thành quả.',1),end('Bài học đắt giá','Bản hợp đồng chưa đọc hết','Sự vội vàng lấy đi vốn và niềm tin của đối tác. Bạn khép sổ, ghi lại từng điều khoản từng bỏ qua trước khi nghĩ tới lần bắt đầu mới.','Tương lai không trả thay những khoản nợ hiện tại.',-Infinity)]},
};
export function pickDemoEnding(genre,stats){
 if(genre.death && stats[genre.death]<=0)return genre.deathEnding;
 return genre.endings.find(e=>(stats[genre.score]??0)>=e.min)||genre.endings.at(-1);
}
