// Image-free presentation studies. No remote assets or production theme registration.
const choice=(text,score)=>({text,modifiers:{resolve:score}});
const scene=(title,place,time,paragraphs,quote,choices)=>({title,place,time,paragraphs,quote,choices:choices.map(([text,value])=>choice(text,value))});
const endings=(good,quiet)=>[
 {label:'Trọn vẹn',title:good[0],paragraphs:[good[1]],quote:good[2],min:5},
 {label:'Còn tiếp',title:quiet[0],paragraphs:[quiet[1]],quote:quiet[2],min:-Infinity},
];
export const patternDemos={
 letters:{id:'letters',pattern:true,audio:'storybook',label:'Không ảnh · Hiện đại — Thư gửi ngày mai',title:'Thư gửi ngày mai',description:'Giấy thư hiện đại, đường kẻ mảnh và tem hình học. Lựa chọn như những dòng hồi âm.',kicker:'BƯU PHẨM CHƯA GỬI',motif:'letter',score:'resolve',stats:[{key:'resolve',label:'Chân thành',initial:0}],scenes:[
 scene('Một lá thư để quên','Quán cà phê góc phố','Thứ Bảy · 16:20',['Giữa những tờ giấy chuyển nhà, bạn tìm thấy một phong thư chưa dán tem. Người nhận là người bạn từng hứa sẽ gặp lại sau lễ tốt nghiệp.','Ngoài cửa kính, thành phố vẫn ồn ào. Số điện thoại trên phong thư có thể đã đổi, nhưng quán cà phê hẹn năm ấy vẫn còn ở đây.'],'Có những lời, chậm một chút vẫn nên nói.',[['Viết lại lời xin lỗi bằng những điều thật lòng.',3],['Gửi một lời hỏi thăm ngắn trước.',1],['Cất thư lại, đợi một ngày phù hợp hơn.',-1]]),
 scene('Chiếc ghế đối diện','Cùng một góc phố','Chủ Nhật · 10:00',['Tin nhắn trả lời đến vào sáng sớm: “Mười giờ, chỗ cũ nhé.” Bạn đến trước, gọi hai cốc nước rồi đổi ý, để người ấy tự chọn.','Tiếng chuông cửa vang lên. Người đứng ở đó khác trong ký ức, nhưng cách mỉm cười thì không.'],'Lần này, mình có thể bắt đầu từ hiện tại không?',[['Lắng nghe cuộc sống của người ấy trước khi kể về mình.',3],['Nhắc lại một kỷ niệm vui để mở lời.',1],['Giả vờ như khoảng lặng nhiều năm chưa từng xảy ra.',-2]])],endings:endings(['Đã đến đúng người','Lá thư nằm giữa bàn, không cần tem nữa. Hai người kể về những năm đã qua, không vội đòi lại điều từng bỏ lỡ.','Ngày mai, lại cùng uống cà phê nhé.'],['Địa chỉ của ngày mai','Cuộc gặp ngắn hơn bạn nghĩ. Trước lúc rời đi, người ấy để lại số điện thoại mới. Một lời chào chưa phải là lời hứa, nhưng cũng không phải kết thúc.','Lần tới, hãy cứ nhắn cho mình.'])},
 jade:{id:'jade',pattern:true,audio:'palace',label:'Không ảnh · Cổ trang — Ngọc giản',title:'Ngọc giản lưu danh',description:'Khung cửa song, nét mây và dấu son trên giấy ngọc. Cảnh như một thiên truyện, hồi kết như trang lưu bút.',kicker:'THIÊN THỨ NHẤT · GẶP GỠ',motif:'jade',score:'resolve',stats:[{key:'resolve',label:'Tín nghĩa',initial:0}],scenes:[
 scene('Người khách bên đình','Trường Phong đình','Cuối thu · Giờ Dậu',['Người khách đặt một nửa miếng ngọc lên bàn đá. Vết nứt trên đó khớp với miếng ngọc sư phụ để lại cho bạn, nhưng người này không chịu nói tên.','Gió lùa qua song cửa. Dưới chân núi, đoàn người cầm đuốc đang tiến về phía đình.'],'Ta chỉ xin người giữ lời hẹn cũ.',[['Hỏi rõ lời hẹn trước khi quyết định giúp.',3],['Mời khách nghỉ, chờ sư huynh về phân xử.',1],['Đòi đổi miếng ngọc lấy bí mật của môn phái.',-2]]),
 scene('Một lời trước bình minh','Bến đò Thanh Khê','Đầu đông · Giờ Mão',['Bạn tìm thấy bức thư trong hốc cây đúng như lời khách nói. Sư phụ từng hứa đưa một đứa trẻ rời khỏi vòng tranh chấp, không phải trao bí kíp cho bất kỳ ai.','Ở bến đò, người khách đứng cùng cô bé ôm chiếc tay nải nhỏ. Chuyến đò đầu tiên sắp rời bến.'],'Điều cần giữ không phải miếng ngọc.',[['Đưa hai người qua sông rồi trở về giải thích với môn phái.',3],['Chỉ đường vòng để họ tự rời đi.',1],['Giữ họ lại chờ đoàn truy đuổi tới.',-3]])],endings:endings(['Tín nghĩa còn xanh','Hai nửa ngọc được đặt lại bên bàn thờ sư phụ. Bạn không nhận bí kíp hay danh vị, chỉ nhận một lá thư báo bình an khi mùa xuân tới.','Có lời hứa không cần khắc vào đá.'],['Một nét mực chưa khô','Bến đò đã vắng. Bạn trở về cùng câu hỏi về lời hẹn năm xưa, quyết định tự mình tìm đủ những người còn nhớ chuyện cũ.','Giang hồ vẫn còn một đoạn đường.'])},
 orbit:{id:'orbit',pattern:true,audio:'system',label:'Không ảnh · Viễn tưởng — Quỹ đạo',title:'Tín hiệu phía chân trời',description:'Lưới tọa độ, vòng quỹ đạo và bảng truyền tin. Chữ rõ trên nền đêm, hồi kết là thông điệp lưu trữ.',kicker:'TRẠM TIẾP ÂM / 07',motif:'orbit',score:'resolve',stats:[{key:'resolve',label:'Độ tin cậy dữ liệu',initial:0}],scenes:[
 scene('Tín hiệu không có người gửi','Trạm Khe Sáng','Chu kỳ 208 · 03:14',['Ăng-ten thu được một chuỗi tín hiệu lặp lại sau mỗi mười bảy giây. Nó mang mã nhận dạng của con tàu đã mất tích trước khi bạn ra đời.','Bộ nhớ trạm chỉ đủ giữ một bản ghi đầy đủ. Ngoài cửa quan sát, không có điểm sáng nào chuyển động.'],'Xác minh trước khi hồi đáp.',[['Lưu tín hiệu gốc và đối chiếu kho dữ liệu.',3],['Gửi một gói tin hỏi danh tính.',1],['Ghi đè dữ liệu cũ để khuếch đại ngay.',-2]]),
 scene('Khoảng lặng mười bảy giây','Buồng truyền tin','Chu kỳ 208 · 04:02',['Một phần thông điệp đã được giải mã. Đó không phải lời cầu cứu, mà là chỉ dẫn tránh vùng nhiễu sắp đi qua trạm.','Bạn có thể truyền cảnh báo cho mạng lưới, nhưng phải nói rõ phần nào còn chưa xác minh.'],'Không phải mọi khoảng trống đều nên được lấp bằng suy đoán.',[['Gửi dữ liệu cùng mức độ chắc chắn và bản ghi gốc.',3],['Cảnh báo ngắn, hẹn bổ sung bằng chứng.',1],['Công bố phỏng đoán như một kết luận chắc chắn.',-3]])],endings:endings(['Thông điệp đã nhận','Các trạm xác nhận đã đổi hướng an toàn. Trong kho lưu trữ, thông điệp mang cả mã tàu cũ lẫn chữ ký người đã lắng nghe nó sau nhiều năm.','Không còn tín hiệu đơn độc.'],['Chờ lần truyền tiếp theo','Mạng lưới đã nhận bản cảnh báo chưa hoàn chỉnh. Bạn giữ nguyên tần số và chuẩn bị bộ nhớ cho lần tín hiệu quay lại.','Kênh liên lạc vẫn mở.'])},
 nocturne:{id:'nocturne',pattern:true,audio:'mystery',label:'Không ảnh · Đô thị huyền bí — Dạ khúc',title:'Dạ khúc không tên',description:'Hình học Art Deco, vòm sân khấu và đường viền đồng. Lựa chọn như những thẻ mời; kết thúc hạ màn.',kicker:'NHÀ HÁT SAU NỬA ĐÊM',motif:'deco',score:'resolve',stats:[{key:'resolve',label:'Mảnh ký ức',initial:0}],scenes:[
 scene('Tấm vé không ghi ngày','Nhà hát Ánh Đồng','23:55',['Bạn nhận được tấm vé màu đen trong phong bì không đề tên. Trên sân khấu, chiếc đàn piano tự ngân lên đúng giai điệu mẹ bạn thường hát.','Người soát vé chỉ vào hàng ghế trống: “Mỗi vị khách được hỏi hai câu. Hãy dùng chúng cẩn thận.”'],'Bạn đến để nghe, hay để nhớ?',[['Hỏi ai đã gửi tấm vé và giữ lại phong bì.',3],['Ngồi xuống nghe hết bản nhạc.',1],['Đòi gặp người chơi đàn ngay lập tức.',-1]]),
 scene('Nốt nhạc cuối cùng','Sau bức màn nhung','00:07',['Phía sau sân khấu không có nhạc công. Chỉ có chiếc máy ghi âm cũ và cuốn sổ liệt kê tên những người từng gửi nhạc tới nhà hát.','Trong cuốn sổ, bên cạnh tên mẹ là một dòng địa chỉ đã bị gạch bỏ. Dưới lớp mực vẫn còn đọc được tên con phố.'],'Một ký ức không cần hoàn hảo mới đáng giữ.',[['Chép lại địa chỉ rồi xin mang bản ghi về.',3],['Giữ giai điệu trong trí nhớ và rời đi.',1],['Xóa dòng tên để không ai tìm thấy nữa.',-3]])],endings:endings(['Khúc nhạc trở về','Sáng hôm sau, bạn tìm được căn nhà trong sổ. Người mở cửa nhận ra giai điệu trước khi nhận ra tên mẹ bạn. Câu chuyện còn thiếu cuối cùng cũng có người kể tiếp.','Xin dành bản nhạc này cho người đã trở về.'],['Hẹn ở màn sau','Nhà hát đóng cửa khi đồng hồ điểm một giờ. Tấm vé trong tay vẫn chưa bị xé, và bạn biết mình còn một câu hỏi chưa dám nói thành lời.','Đêm mai, đèn lại sáng.'])},
};
